max_length: 6
accu_grad: 0

network_audio:
  backbone: tfnet
  stft_frame: 1024
  stft_hop: 512
  n_fft: 2048
  ngf: 64
  input_nc: 2
  output_nc: 4
  cond_dim: 128
  activation: "Tanh"
  bottleneck_blocks: 4
  bottleneck_residual: true
  bottleneck_attention: true
  attention_reduction: 8
  attention_kernel: 7



vector_cue: 1
sstask: 1
input_mono: 0
stereo_loss: 0


# optimizer
loss_type: pit_sisnr      # "snr", "sisdr", "hybrid"
init_learning_rate: 0.001
max_epoch: 400 


#dataset
dataset:
  path: /home/qysun/Neuro-SS/baseline/multi-channel/sound-bubble/dataset/
  name: mix_sources_updated.csv
  type: online  # 'online' to load from CSV, 'pickle' to load from pkl files

dataloader:
  batch_size: 8
  num_workers: 8


checkpoint_dir: ./checkpoints/